declare sub ConsolePutChar(b as unsigned byte)
Declare Sub ConsoleWrite(s As Unsigned Byte Ptr)
Declare Sub ConsoleWriteLine(s As Unsigned Byte Ptr)
Declare Sub ConsoleWriteNumber(n As Unsigned Integer,b As Unsigned Integer)
Declare Sub ConsoleNewLine()
declare sub ConsolePrintOK()
declare sub ConsoleBackSpace()
declare sub ConsoleSetForeground(c as unsigned integer)
declare sub ConsoleSetBackground(c as unsigned integer)